#!/usr/bin/env python3
"""
Test script for Microsoft calendar execution.

Usage:
  python test_ms_calendar_execute.py
  python test_ms_calendar_execute.py --start-iso 2026-01-15T16:00:00-05:00 --end-iso 2026-01-15T17:00:00-05:00
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    import requests
except ImportError:
    print("ERROR: 'requests' library not found. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

sys.path.insert(0, str(Path(__file__).parent))
try:
    from test_ingest_full import (
        get_stack_output,
        load_auth_config,
        get_tokens_via_pkce,
    )
except ImportError:
    print("ERROR: Could not import from test_ingest_full.py. Make sure it exists.", file=sys.stderr)
    sys.exit(1)


def generate_node_id():
    import uuid

    timestamp_hex = hex(int(time.time() * 1000))[2:]
    random_suffix = uuid.uuid4().hex[:8]
    return f"node_{timestamp_hex}_{random_suffix}"


def resolve_start_end(start_iso, end_iso):
    if start_iso and end_iso:
        return start_iso, end_iso
    start_dt = datetime.now(timezone.utc) + timedelta(minutes=15)
    end_dt = start_dt + timedelta(hours=1)
    return start_dt.isoformat(), end_dt.isoformat()


def build_calendar_node(node_id, start_iso, end_iso):
    now_iso = datetime.now(timezone.utc).isoformat()
    return {
        "schema_version": "braindump.node.v1",
        "node_type": "ms_calendar",
        "title": "Test Microsoft Calendar Event",
        "body": "Test Microsoft calendar event created by script",
        "tags": ["test", "calendar", "ms"],
        "status": "active",
        "confidence": 0.9,
        "evidence": [{"quote": "Test Microsoft calendar event"}],
        "location_context": {"location_used": False},
        "time_interpretation": {
            "original_text": "test time",
            "kind": "datetime",
            "needs_clarification": False,
            "resolved_start_iso": start_iso,
            "resolved_end_iso": end_iso,
        },
        "ms_calendar": {
            "event_title": "Test Microsoft Calendar Event",
            "intent": "Create a test Microsoft calendar event",
            "start": {
                "original_text": "test time",
                "kind": "datetime",
                "needs_clarification": False,
                "resolution_notes": "Generated by test script",
            },
            "start_datetime_iso": start_iso,
            "end_datetime_iso": end_iso,
            "duration_minutes": 60,
            "location_text": "Test location",
            "attendees_text": ["test@example.com"],
        },
        "global_warnings": [],
        "created_at_iso": now_iso,
        "captured_at_iso": now_iso,
        "timezone": "+00:00",
        "node_id": node_id,
        "parse_debug": {
            "model_id": "test-script",
            "latency_ms": 0,
            "tool_name_used": "test",
            "fallback_used": False,
        },
    }


def resolve_api_url(stack_name, api_url):
    if api_url:
        return api_url
    return get_stack_output(stack_name, "ApiEndpoint")


def call_api(api_url, token, node, node_id, mode):
    if not api_url.endswith("/"):
        api_url += "/"
    if mode == "execute":
        url = f"{api_url}node/{node_id}/execute"
    else:
        url = f"{api_url}node/{node_id}/complete"

    payload = {
        "node": node,
        "node_id": node_id,
        "captured_at_iso": node.get("captured_at_iso"),
    }

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    print(f"\n=== Request ===")
    print(f"URL: {url}")
    print(f"Mode: {mode}")
    print(f"Node ID: {node_id}")

    response = requests.post(url, headers=headers, json=payload, timeout=30)
    print(f"\n=== Response ===")
    print(f"Status Code: {response.status_code}")
    try:
        data = response.json()
        print(json.dumps(data, indent=2))
    except ValueError:
        print(response.text)
        data = None

    return response, data


def main() -> int:
    parser = argparse.ArgumentParser(description="Test Microsoft calendar execution")
    parser.add_argument("--api-url", default=os.environ.get("API_URL"))
    parser.add_argument("--stack-name", default=os.environ.get("STACK_NAME", "second-brain-backend-evan"))
    parser.add_argument("--token", default=os.environ.get("ID_TOKEN") or os.environ.get("ACCESS_TOKEN"))
    parser.add_argument("--auth-config")
    parser.add_argument("--mode", choices=["complete", "execute"], default="complete")
    parser.add_argument("--start-iso")
    parser.add_argument("--end-iso")
    args = parser.parse_args()

    api_url = resolve_api_url(args.stack_name, args.api_url)
    if not api_url:
        print("ERROR: API URL not found. Set API_URL or STACK_NAME.", file=sys.stderr)
        return 1

    token = args.token
    if not token:
        auth_config_path = args.auth_config
        if not auth_config_path:
            repo_root = Path(__file__).resolve().parents[2]
            auth_config_path = repo_root / "frontend" / "auth.config.json"
        auth_config = load_auth_config(auth_config_path)
        if not auth_config:
            print(f"ERROR: Could not load auth config from {auth_config_path}", file=sys.stderr)
            return 1
        tokens = get_tokens_via_pkce(auth_config)
        token = tokens.get("id_token")
    if not token:
        print("ERROR: Could not obtain auth token.", file=sys.stderr)
        return 1

    start_iso, end_iso = resolve_start_end(args.start_iso, args.end_iso)
    node_id = generate_node_id()
    node = build_calendar_node(node_id, start_iso, end_iso)

    response, _ = call_api(api_url, token, node, node_id, args.mode)
    return 0 if response.status_code < 300 else 2


if __name__ == "__main__":
    raise SystemExit(main())
