#!/usr/bin/env python3
"""
Test script for calendar execution via complete_node or execute_node.

Usage:
  python test_calendar_execute.py
  python test_calendar_execute.py --mode complete
  python test_calendar_execute.py --mode execute
  python test_calendar_execute.py --token YOUR_ID_TOKEN
  python test_calendar_execute.py --start-iso 2026-01-15T16:00:00-05:00 --end-iso 2026-01-15T17:00:00-05:00
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    import requests
except ImportError:
    print("ERROR: 'requests' library not found. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

sys.path.insert(0, str(Path(__file__).parent))
try:
    from test_ingest_full import (
        get_stack_output,
        load_auth_config,
        get_tokens_via_pkce,
    )
except ImportError:
    print("ERROR: Could not import from test_ingest_full.py. Make sure it exists.", file=sys.stderr)
    sys.exit(1)

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
try:
    from lib.auth import verify_token
except ImportError:
    print("ERROR: Could not import verify_token from lib.auth", file=sys.stderr)
    sys.exit(1)


def generate_node_id():
    import uuid

    timestamp_hex = hex(int(time.time() * 1000))[2:]
    random_suffix = uuid.uuid4().hex[:8]
    return f"node_{timestamp_hex}_{random_suffix}"


def extract_user_id_from_token(token):
    try:
        claims = verify_token(token)
        return claims.get("sub", "")
    except Exception:
        return ""


def build_calendar_node(node_id, start_iso, end_iso):
    now_iso = datetime.now(timezone.utc).isoformat()
    return {
        "schema_version": "braindump.node.v1",
        "node_type": "calendar_placeholder",
        "title": "Test Calendar Event",
        "body": "Test calendar event created by script",
        "tags": ["test", "calendar"],
        "status": "active",
        "confidence": 0.9,
        "evidence": [{"quote": "Test calendar event"}],
        "location_context": {"location_used": False},
        "time_interpretation": {
            "original_text": "test time",
            "kind": "datetime",
            "needs_clarification": False,
            "resolved_start_iso": start_iso,
            "resolved_end_iso": end_iso,
        },
        "calendar_placeholder": {
            "event_title": "Test Calendar Event",
            "intent": "Create a test calendar event",
            "start": {
                "original_text": "test time",
                "kind": "datetime",
                "needs_clarification": False,
                "resolution_notes": "Generated by test script",
            },
            "start_datetime_iso": start_iso,
            "end_datetime_iso": end_iso,
            "duration_minutes": 60,
            "location_text": "Test location",
            "attendees_text": ["test@example.com"],
        },
        "global_warnings": [],
        "created_at_iso": now_iso,
        "captured_at_iso": now_iso,
        "timezone": "+00:00",
        "node_id": node_id,
        "parse_debug": {
            "model_id": "test-script",
            "latency_ms": 0,
            "tool_name_used": "test",
            "fallback_used": False,
        },
    }


def resolve_start_end(start_iso, end_iso):
    if start_iso and end_iso:
        return start_iso, end_iso
    start_dt = datetime.now(timezone.utc) + timedelta(minutes=15)
    end_dt = start_dt + timedelta(hours=1)
    return start_dt.isoformat(), end_dt.isoformat()


def call_api(api_url, token, node, node_id, mode):
    if not api_url.endswith("/"):
        api_url += "/"
    if mode == "execute":
        url = f"{api_url}node/{node_id}/execute"
    else:
        url = f"{api_url}node/{node_id}/complete"

    payload = {
        "node": node,
        "node_id": node_id,
        "captured_at_iso": node.get("captured_at_iso"),
    }

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    print(f"\n=== Request ===")
    print(f"URL: {url}")
    print(f"Mode: {mode}")
    print(f"Node ID: {node_id}")

    response = requests.post(url, headers=headers, json=payload, timeout=30)
    print(f"\n=== Response ===")
    print(f"Status Code: {response.status_code}")
    try:
        data = response.json()
        print(json.dumps(data, indent=2))
    except ValueError:
        print(response.text)
        data = None

    return response, data


def main():
    parser = argparse.ArgumentParser(description="Test calendar execution")
    parser.add_argument("--api-url", default=os.environ.get("API_URL"))
    parser.add_argument("--stack-name", default=os.environ.get("STACK_NAME", "second-brain-backend-evan"))
    parser.add_argument("--token", default=os.environ.get("ID_TOKEN") or os.environ.get("ACCESS_TOKEN"))
    parser.add_argument("--token-type", choices=["id", "access"], default="id")
    parser.add_argument("--auth-config", default=os.environ.get("AUTH_CONFIG"))
    parser.add_argument("--node-id", default=None)
    parser.add_argument("--mode", choices=["complete", "execute"], default="complete")
    parser.add_argument("--start-iso", default=None)
    parser.add_argument("--end-iso", default=None)
    parser.add_argument("--no-browser", action="store_true")

    args = parser.parse_args()

    auth_config_path = args.auth_config
    if not auth_config_path:
        repo_root = Path(__file__).resolve().parents[2]
        auth_config_path = repo_root / "frontend" / "auth.config.json"

    api_url = args.api_url
    if not api_url:
        print("Fetching API URL from CloudFormation stack...")
        api_url = get_stack_output(args.stack_name, "ApiEndpoint")
        if not api_url:
            print("ERROR: Could not resolve API URL.")
            sys.exit(1)

    token = args.token
    if not token:
        config = load_auth_config(auth_config_path)
        if not config:
            print(f"ERROR: Could not load auth config from {auth_config_path}")
            sys.exit(1)
        tokens = get_tokens_via_pkce(config, open_browser=not args.no_browser)
        token = tokens.get("id_token") if args.token_type == "id" else tokens.get("access_token")
        if not token:
            print("ERROR: Token missing from OAuth response.")
            sys.exit(1)

    user_id = extract_user_id_from_token(token)
    if user_id:
        print(f"User ID: {user_id}")

    node_id = args.node_id or generate_node_id()
    start_iso, end_iso = resolve_start_end(args.start_iso, args.end_iso)
    node = build_calendar_node(node_id, start_iso, end_iso)

    response, data = call_api(api_url, token, node, node_id, args.mode)

    print("\n=== Summary ===")
    if response.status_code == 200:
        print("✅ SUCCESS")
        if data and data.get("calendar_event"):
            print(f"Calendar event id: {data['calendar_event'].get('id')}")
            print(f"Calendar event link: {data['calendar_event'].get('html_link')}")
    else:
        print(f"❌ FAILED: HTTP {response.status_code}")
        if data and "error" in data:
            print(f"Error: {data['error']}")


if __name__ == "__main__":
    main()
